// Semeia/cura o SEGUNDO CÉREBRO do Hermes (conhecimento supervisionado pelo Claude, read-only p/ Hermes).
// Idempotente (upsert por tópico). Rode quando quiser atualizar a curadoria: npx tsx scripts/seed-cerebro.ts
import { curarCerebro } from '../src/lib/cerebro'
import { prisma } from '../src/lib/db'

const CARDS: [string, string, number][] = [
  ['honestidade', 'Indício não é acusação. INDISPONÍVEL ≠ 0. Nunca inventar número. CPF mascarado. Toda afirmação forte precisa de fonte verificável. Vale para conteúdo, denúncia e análise.', 1.0],
  ['viral-lei-do-perfil', 'SEND = "isto sou EU, meu grupo precisa ver" (identidade + emoção de alta ativação). SAVE = "vou precisar depois" (valor prático). Like é morto. NESTE perfil: saturados (muito uso, pouco retorno) = unidade/tribo, frase-bandeira, indignação genérica. SUBUSADOS de alto potencial = INIMIGO COMUM institucional (+67% share), AWE/número de choque, URGÊNCIA. Combo-ouro: custo de vida + desperdício/corrupção do dinheiro público.', 1.0],
  ['guarda-etica-viral', 'Indignação SEMPRE ancorada em fato verificável (documento/processo/dado público). Inimigo = conduta/sistema/abuso, NUNCA grupo identitário vulnerável. Nunca afirmar o não-checado: desinformação explora a indignação e expõe o mandato. Dosar: indignação p/ send, valor prático p/ save, awe p/ arejar.', 1.0],
  ['ecossistema-jedi', 'PolitiMonitor (Hermes viral: analisa/aprende/recomenda posts IG) + JFN (fiscalização: Yoda, Lex=pareceres, compliance, sweeps SEI/SIAFE, RAG Lei 14.133) + vault Obsidian (segundo cérebro do Claude). Hermes roda em modelo grátis na VM (2 vCPU — não crashar).', 0.8],
  ['como-operamos-juntos', 'Claude e Hermes operam em conjunto, um dando inteligência ao outro. Hermes APRENDE dos dados reais (sends/saves) e escreve só a memória dele (viral/playbook). Claude SUPERVISIONA: revisa o que o Hermes aprendeu e PROMOVE o validado ao segundo cérebro (curar). Hermes CONSULTA o cérebro (read-only) e nunca o sobrescreve. A guarda em lembrar() bloqueia escrita do Hermes em conhecimento supervisionado.', 0.9],

  // --- Cherry-pick de conhecimento externo (social-media-skills / marketingskills), universalizado ao nosso contexto.
  //     Vetados por segurança e fatiados como conceito — pacotes NÃO instalados (regra: VM leve + economia de token).
  ['ganchos-arquetipos', 'Os 6 arquétipos de gancho (universais, adaptados ao perfil) — variar entre eles (+40% viral recorrente): 1) NÚMERO DE CHOQUE: abrir com o valor ("R$ X sumiram do hospital Y"). 2) CONTRARIAN: crença + virada ("Todo mundo acha que X. Mentira:"). 3) TRANSFORMAÇÃO: antes×depois com dígito. 4) ROUBO DE AUTORIDADE: citar nome/fonte ("Segundo o TCE...", "consta no processo nº"). 5) ADMISSÃO/DENÚNCIA: revelar o que escondem ("O que NÃO querem que você saiba sobre..."). 6) FUTURE SHOCK: previsão/ameaça concreta ("Se isso passar, sua conta de luz sobe"). Linha 1 prende em <3s; linha 2 contrasta/aprofunda.', 0.9],
  ['reverse-engineer-outlier', 'Validado externamente (reels-scripting): pegar um reel OUTLIER (que viralizou) e decompor com framework FIXO — (a) TRANSCRIPT completo; (b) GANCHO: 1ªs palavras + contagem + por que para o scroll em <3s; (c) PADRÃO DE LINGUAGEM: frases curtas, razão você/eu, transições; (d) ESTRUTURA: duração, seções com tempo, momento antes/depois, CTA; (e) 1 INSIGHT-CHAVE a roubar. Nosso analista já avalia métricas de graça (Graph API, sem Apify pago); o ganho é aplicar ESTE checklist de decomposição ao analisar referências (benchmark.ts) e ao gerar roteiro.', 0.8],
  ['economia-caveman', 'Princípio de economia (do caveman, fatiado com cuidado): ser TERSO onde a saída é FUNCIONAL/interna (prompts de estruturação, decisão, JSON — corta ~75% de token sem perder precisão). NUNCA terso no que é USER-FACING (relatórios, legendas, conteúdo, prosa) — ali qualidade > economia (regra estética absoluta do dono). NÃO instalar o skill caveman global (terseariza tudo + traz hooks/MCP que pesam o input). Aplicar só caso a caso nos passos internos.', 0.7],
  ['matriz-de-formatos', 'Matriz pilar×formato (content-matrix) — VARIAR os 8 formatos p/ não repetir e cobrir ângulos: 1) ACIONÁVEL (como-fazer ultra-específico). 2) MOTIVACIONAL (história de quem fez algo extraordinário). 3) ANALÍTICO (por que X funciona/falha assim). 4) CONTRARIAN (contra o senso comum, com prova). 5) OBSERVAÇÃO (tendência silenciosa que ninguém comenta). 6) X vs Y (comparar dois — gestão A×B, antes×agora, RJ×outro estado). 7) PRESENTE vs FUTURO (estado atual × previsão concreta com o porquê). 8) LISTICLE (lista de erros/provas/passos/recursos). Cada ideia = MANCHETE específica, não tema. No nosso caso, ancorar no fiscalizatório (gasto público, serviço, Zona Oeste).', 0.8],
  ['modelos-mentais', 'Modelos mentais p/ estratégia de conteúdo/campanha (marketing-psychology, filtrados): JOBS-TO-BE-DONE (o eleitor não quer um post, quer sentir-se representado e munido — foque no "serviço" que o conteúdo presta). PARETO 80/20 (20% dos temas/horários dão 80% do alcance — dobrar neles, cortar o resto). TEORIA DAS RESTRIÇÕES (achar o gargalo do funil — se alcance alto e save baixo, o problema é valor prático, não tráfego). INVERSÃO (listar o que GARANTE o fracasso do post — mensagem confusa, sem fato, sem CTA — e evitar cada um). PRIMEIROS PRINCÍPIOS (não copiar concorrente; perguntar "por quê" até a verdade básica).', 0.7],

  // --- 2ª leva de canibalização (Fase 1.3): 5 nuggets de ouro do sweep das 62 skills.
  ['scoring-top-decil', 'Scoring contra o PRÓPRIO top-10% real (post-scorer, sem Apify pago): calcular engagement_score = reactions + comments×3 sobre o histórico Graph API; extrair os padrões do decil superior (tipos de gancho, comprimento, CTA, clusters de tema, ritmo); cada crítica do analista CITA o data point ("seus hits usam gancho número-de-choque em 42%; este draft usa pergunta em 12%") em vez de conselho genérico. Baseline = nossos próprios vencedores, não best-practice de fora.', 0.8],
  ['comentario-fixado-satirico', 'Engine de comentário-fixado satírico (pinned-comment): a IMAGEM carrega a piada, o TEXTO legenda o fato. O alvo (gestor/órgão) sempre em status mais baixo. 5 testes de QA antes de aprovar: (1) gag ≤5 palavras? (2) legenda um fato verificável? (3) o alvo é o "loser" da piada? (4) funciona sem alcance viral? (5) some a imagem — ainda tem graça? Não passou → refaz. SEMPRE ancorado em documento/processo/dado público (guarda ética).', 0.7],
  ['infografico-quadro-branco', 'Template visual "quadro-branco denúncia" (gemini-infographic): prompt = foto de um quadro branco REAL, marcador colorido, linhas imperfeitas, SEM fontes digitais — estética orgânica anti-press-release. Transforma achado de auditoria (Empenho≠Liquidação≠OB, valores desviados) em infográfico que escapa do visual "nota oficial". Parametrizar: título ≤6 palavras, 3-7 bullets ≤10 palavras, números-chave destacados em círculo.', 0.7],
  ['content-atoms', '1 fato → N peças (social/content-atoms): de UM parecer/achado longo, extrair 5-10 "átomos" autônomos (cada um se sustenta sozinho) e virar carrossel + Reel + thread + comentário. E de 1 fato gerar 4 ganchos rotulados (Contrarian / Curiosidade / "Pare de X, faça Y" / Número-de-choque), escolhendo pelo desempenho real (SEND/SAVE), não pelo gosto. Repurposing 1→N multiplica alcance sem novo fato.', 0.8],
  ['money-quotes', 'Mineração de "money quotes" verbatim (customer-research): minerar comentários/Reddit/respostas locais por DOR em linguagem emocional e guardar 5-10 citações textuais por tema. Usar a fala REAL do eleitor ("minha creche caiu enquanto pagavam R$X") como gancho de indignação ancorada, no lugar de jargão fiscal — a linguagem do cidadão > a nossa. Sempre casar a citação com o fato verificável.', 0.7],
]

;(async () => {
  for (const [topico, conteudo, rel] of CARDS) await curarCerebro(topico, conteudo, rel)
  const n = await prisma.hermesMemoria.count({ where: { tipo: 'cerebro' } })
  console.log(`[seed-cerebro] ${CARDS.length} cartões curados. Total no cérebro: ${n}`)
  await prisma.$disconnect()
  process.exit(0)
})().catch((e) => { console.error('erro:', e instanceof Error ? e.message : e); process.exit(1) })
